### ISSUE TITLE
Add usage sections in readme

### ISSUE THREAD

**Issue by Zane-XY** [krzema12/snakeyaml-engine-kmp#124]
Hi could you please add a section in readme on how to serialize and deserialize in Kotlin? I really want to have a try.

**Comment by aSemy** [comment]
Hi @Zane-XY 👋 


This information should be added to the README:

snakeyaml-engine-kmp is quite low-level. You can take a look at an example usage in an end-to-end test https://github.com/krzema12/snakeyaml-engine-kmp/blob/v2.7.1/src/commonTest/kotlin/org/snakeyaml/engine/SimpleEndToEndTest.kt

If you want to encode/decode YAML with Kotlin, then it's best to use https://github.com/charleskorn/kaml. snakeyaml-engine-kmp was converted from Java specifically for Kaml.

**Comment by krzema12** [comment]
There's actually some higher-level API as well, see the example:

https://github.com/typesafegithub/github-actions-typing-catalog/blob/1f94a9e94fb4bb38dffe42f217fe1735161af624/.github/workflows/update-metadata.main.kts#L77

I haven't tried parsing yet.

I'll try to come up with some quick examples for both APIs so that we can inline them in the README for convenience.

**Comment by Zane-XY** [comment]
Thanks @aSemy , @krzema12 .
